model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 0.000001
        disc_weight: 0.5
        disc_in_channels: 1
        perceptual_weight: 0.0

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [ 1, 2, 4, 4 ]  # f = 2^3 = 8 downsampling
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    wrap: True
    train:
      target: ChestXRay.ChestXrayDataset  # <--- Your Class
      params:
        root_dir: "/datasets/mmolefe/cleaned"   # Update this path
        task: "All_CXR"
        split: "train"
        img_size: 256
    validation:
      target: ChestXRay.ChestXrayDataset
      params:
        root_dir: "/datasets/mmolefe/cleaned"
        task: "All_CXR"
        split: "val"
        img_size: 256

lightning:
  logger:
    target: pytorch_lightning.loggers.WandbLogger
    params:
      name: chest-xray-vae
      save_dir: logs
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2